<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260610112949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, type VARCHAR(20) NOT NULL, path VARCHAR(500) DEFAULT NULL, date DATE NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76979B1AD6 ON document (company_id)');
        $this->addSql('CREATE TABLE task_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_name VARCHAR(100) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B9578868DB60186 ON task_comment (task_id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_comment ADD CONSTRAINT FK_8B9578868DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE company ADD kind VARCHAR(20) DEFAULT \'hersteller\' NOT NULL');
        $this->addSql('ALTER TABLE company ADD subtitle VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD tags JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE company ADD custom_fields JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE company ADD note TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE contact ADD department VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE task ADD tags JSON DEFAULT \'[]\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76979B1AD6');
        $this->addSql('ALTER TABLE task_comment DROP CONSTRAINT FK_8B9578868DB60186');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE task_comment');
        $this->addSql('ALTER TABLE company DROP kind');
        $this->addSql('ALTER TABLE company DROP subtitle');
        $this->addSql('ALTER TABLE company DROP tags');
        $this->addSql('ALTER TABLE company DROP custom_fields');
        $this->addSql('ALTER TABLE company DROP note');
        $this->addSql('ALTER TABLE contact DROP department');
        $this->addSql('ALTER TABLE task DROP tags');
    }
}
