<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Dateien an Aufgaben anhängen. */
final class Version20260621210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'task_file: an Aufgaben angehängte Dateien';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE task_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_id INT NOT NULL, filename VARCHAR(255) NOT NULL, content_type VARCHAR(150) DEFAULT NULL, size INT NOT NULL, path VARCHAR(500) NOT NULL, uploaded_by VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_TASKFILE_TASK ON task_file (task_id)');
        $this->addSql('ALTER TABLE task_file ADD CONSTRAINT FK_TASKFILE_TASK FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE task_file DROP CONSTRAINT FK_TASKFILE_TASK');
        $this->addSql('DROP TABLE task_file');
    }
}
