<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Verwaltbare Signaturen + Postfach-Standardsignatur (löst das freie mailbox.signature ab). */
final class Version20260622090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'signature-Tabelle + mailbox.default_signature_id; mailbox.signature entfernt';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE signature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, html TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE mailbox ADD default_signature_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE mailbox ADD CONSTRAINT FK_MAILBOX_SIG FOREIGN KEY (default_signature_id) REFERENCES signature (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_MAILBOX_SIG ON mailbox (default_signature_id)');
        // bestehende Freitext-Signatur (falls gesetzt) in eine Signatur überführen und als Standard setzen
        $this->addSql("INSERT INTO signature (name, html, created_at) SELECT 'Signatur '||name, signature, NOW() FROM mailbox WHERE signature IS NOT NULL AND signature <> ''");
        $this->addSql("UPDATE mailbox m SET default_signature_id = s.id FROM signature s WHERE s.name = 'Signatur '||m.name AND m.signature IS NOT NULL AND m.signature <> ''");
        $this->addSql('ALTER TABLE mailbox DROP signature');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE mailbox ADD signature TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE mailbox DROP CONSTRAINT FK_MAILBOX_SIG');
        $this->addSql('DROP INDEX IDX_MAILBOX_SIG');
        $this->addSql('ALTER TABLE mailbox DROP default_signature_id');
        $this->addSql('DROP TABLE signature');
    }
}
