<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** KI-Nutzung/Kosten erfassen (für Monatsbudget + Reporting). */
final class Version20260622120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'llm_usage: Tokens + geschätzte Kosten je KI-Aufruf';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE llm_usage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, model VARCHAR(60) NOT NULL, input_tokens INT NOT NULL, output_tokens INT NOT NULL, cost_micros INT NOT NULL, feature VARCHAR(40) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_LLMUSAGE_CREATED ON llm_usage (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE llm_usage');
    }
}
