<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260607154400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, roles JSON NOT NULL, description TEXT DEFAULT NULL, represented_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FBF094F42275FE7 ON company (represented_by_id)');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, function VARCHAR(50) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E638979B1AD6 ON contact (company_id)');
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(500) NOT NULL, customer_email VARCHAR(180) DEFAULT NULL, customer_name VARCHAR(200) DEFAULT NULL, status VARCHAR(20) NOT NULL, root_message_id VARCHAR(998) DEFAULT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, mailbox_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E966EC35CC ON conversation (mailbox_id)');
        $this->addSql('CREATE TABLE email (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, direction VARCHAR(4) NOT NULL, from_address VARCHAR(180) DEFAULT NULL, to_address VARCHAR(500) DEFAULT NULL, subject VARCHAR(500) DEFAULT NULL, body_text TEXT DEFAULT NULL, body_html TEXT DEFAULT NULL, message_id VARCHAR(998) DEFAULT NULL, in_reply_to VARCHAR(998) DEFAULT NULL, refs TEXT DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7927C749AC0396 ON email (conversation_id)');
        $this->addSql('CREATE INDEX idx_email_message_id ON email (message_id)');
        $this->addSql('CREATE TABLE mailbox (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, imap_host VARCHAR(180) NOT NULL, imap_port INT NOT NULL, imap_encryption VARCHAR(10) NOT NULL, smtp_host VARCHAR(180) NOT NULL, smtp_port INT NOT NULL, smtp_encryption VARCHAR(10) NOT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity DOUBLE PRECISION DEFAULT NULL, unit VARCHAR(20) DEFAULT NULL, price NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) NOT NULL, tender_id INT DEFAULT NULL, variant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_462CE4F59245DE54 ON position (tender_id)');
        $this->addSql('CREATE INDEX IDX_462CE4F53B69A9AF ON position (variant_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, category VARCHAR(30) DEFAULT NULL, description TEXT DEFAULT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD166D1F9C ON product (project_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, category VARCHAR(30) DEFAULT NULL, status VARCHAR(20) NOT NULL, description TEXT DEFAULT NULL, manufacturer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEA23B42D ON project (manufacturer_id)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, priority VARCHAR(10) NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, assignee_id INT DEFAULT NULL, tender_id INT DEFAULT NULL, company_id INT DEFAULT NULL, conversation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB2559EC7D60 ON task (assignee_id)');
        $this->addSql('CREATE INDEX IDX_527EDB259245DE54 ON task (tender_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25979B1AD6 ON task (company_id)');
        $this->addSql('CREATE INDEX IDX_527EDB259AC0396 ON task (conversation_id)');
        $this->addSql('CREATE TABLE tax_registration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, tax_group VARCHAR(30) DEFAULT NULL, tax_number VARCHAR(50) DEFAULT NULL, eori VARCHAR(50) DEFAULT NULL, covered_countries JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tender (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, countries JSON NOT NULL, won_country_groups JSON NOT NULL, channel VARCHAR(20) DEFAULT NULL, incoterm VARCHAR(10) DEFAULT NULL, stage VARCHAR(20) NOT NULL, deadline DATE DEFAULT NULL, value NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT DEFAULT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42057A779B6B5FBA ON tender (account_id)');
        $this->addSql('CREATE INDEX IDX_42057A77166D1F9C ON tender (project_id)');
        $this->addSql('CREATE TABLE variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, packaging VARCHAR(50) DEFAULT NULL, ean VARCHAR(20) DEFAULT NULL, article_number VARCHAR(50) DEFAULT NULL, net_weight DOUBLE PRECISION DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F143BFAD4584665A ON variant (product_id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F42275FE7 FOREIGN KEY (represented_by_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E966EC35CC FOREIGN KEY (mailbox_id) REFERENCES mailbox (id)');
        $this->addSql('ALTER TABLE email ADD CONSTRAINT FK_E7927C749AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F59245DE54 FOREIGN KEY (tender_id) REFERENCES tender (id)');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F53B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEA23B42D FOREIGN KEY (manufacturer_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2559EC7D60 FOREIGN KEY (assignee_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB259245DE54 FOREIGN KEY (tender_id) REFERENCES tender (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB259AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE tender ADD CONSTRAINT FK_42057A779B6B5FBA FOREIGN KEY (account_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE tender ADD CONSTRAINT FK_42057A77166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE variant ADD CONSTRAINT FK_F143BFAD4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094F42275FE7');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E638979B1AD6');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E966EC35CC');
        $this->addSql('ALTER TABLE email DROP CONSTRAINT FK_E7927C749AC0396');
        $this->addSql('ALTER TABLE position DROP CONSTRAINT FK_462CE4F59245DE54');
        $this->addSql('ALTER TABLE position DROP CONSTRAINT FK_462CE4F53B69A9AF');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD166D1F9C');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEA23B42D');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2559EC7D60');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB259245DE54');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25979B1AD6');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB259AC0396');
        $this->addSql('ALTER TABLE tender DROP CONSTRAINT FK_42057A779B6B5FBA');
        $this->addSql('ALTER TABLE tender DROP CONSTRAINT FK_42057A77166D1F9C');
        $this->addSql('ALTER TABLE variant DROP CONSTRAINT FK_F143BFAD4584665A');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE email');
        $this->addSql('DROP TABLE mailbox');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE tax_registration');
        $this->addSql('DROP TABLE tender');
        $this->addSql('DROP TABLE variant');
    }
}
